package com.lifelink.model;

import java.time.LocalDateTime;

/**
 * Represents a single in-app notification for any user.
 *
 * <p>Notifications are generated by the background matching engine,
 * inventory monitor, and request workflow. They are stored in the
 * {@code notifications} table and polled when the notification panel opens.
 *
 * <p><b>Package:</b> com.lifelink.model
 * <p><b>Used by:</b> NotificationDAO, NotificationService, NotificationController
 */
public class Notification {

    // ── Notification type constants ───────────────────────────────────────────
    public static final String TYPE_EMERGENCY_REQUEST  = "EMERGENCY_REQUEST";
    public static final String TYPE_DONOR_MATCH        = "DONOR_MATCH";
    public static final String TYPE_LOW_STOCK          = "LOW_STOCK";
    public static final String TYPE_REQUEST_APPROVED   = "REQUEST_APPROVED";
    public static final String TYPE_REQUEST_REJECTED   = "REQUEST_REJECTED";
    public static final String TYPE_REQUEST_FULFILLED  = "REQUEST_FULFILLED";
    public static final String TYPE_DONATION_REMINDER  = "DONATION_REMINDER";
    public static final String TYPE_SYSTEM             = "SYSTEM";
    public static final String TYPE_GENERAL            = "GENERAL";

    // ── Fields ────────────────────────────────────────────────────────────────
    private int           notificationId;
    private int           userId;
    private String        title;
    private String        message;
    private String        type;
    private boolean       read;
    private LocalDateTime createdAt;

    public Notification() {}

    public Notification(int userId, String title, String message, String type) {
        this.userId    = userId;
        this.title     = title;
        this.message   = message;
        this.type      = type;
        this.read      = false;
        this.createdAt = LocalDateTime.now();
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public int getNotificationId()                  { return notificationId; }
    public void setNotificationId(int id)           { this.notificationId = id; }

    public int getUserId()                          { return userId; }
    public void setUserId(int uid)                  { this.userId = uid; }

    public String getTitle()                        { return title; }
    public void setTitle(String t)                  { this.title = t; }

    public String getMessage()                      { return message; }
    public void setMessage(String m)                { this.message = m; }

    public String getType()                         { return type; }
    public void setType(String t)                   { this.type = t; }

    public boolean isRead()                         { return read; }
    public void setRead(boolean r)                  { this.read = r; }

    public LocalDateTime getCreatedAt()             { return createdAt; }
    public void setCreatedAt(LocalDateTime dt)      { this.createdAt = dt; }

    @Override
    public String toString() {
        return "Notification{id=" + notificationId + ", userId=" + userId
                + ", type='" + type + "', read=" + read + "}";
    }
}
